name: first workflows
on:
  push:
    branche:
      - main
jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print a welcome message
        run: echo "Welcome to our first github actions workflows"
